channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.01.10
  - cudatoolkit=11.3.1
  - flit-core=3.6.0
  - intel-openmp=2022.1.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2022.1.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=21.2.4
  - python=3.9.7
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - accelerate==0.31.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.8
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.2.1
    - async-lru==2.0.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - babel==2.16.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bertviz==1.4.0
    - bitarray==2.7.3
    - bleach==6.0.0
    - blinker==1.8.2
    - blis==0.7.9
    - boto3==1.35.25
    - botocore==1.35.25
    - bqplot==0.12.43
    - catalogue==2.0.8
    - certifi==2024.8.30
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - click==8.1.3
    - cloudpathlib==0.18.1
    - cloudpickle==3.1.1
    - cmake==3.26.1
    - colorama==0.4.6
    - comm==0.1.2
    - confection==0.0.4
    - contourpy==1.0.7
    - cupy-cuda12x==13.3.0
    - cycler==0.11.0
    - cymem==2.0.7
    - cython==0.29.34
    - datasets==2.21.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.7
    - einops==0.4.0
    - en-core-web-sm==3.7.1
    - executing==1.2.0
    - fairseq==0.12.2
    - fastjsonschema==2.16.2
    - fastrlock==0.8.3
    - filelock==3.9.0
    - flask==3.0.3
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2024.5.0
    - h11==0.14.0
    - higher==0.2.1
    - httpcore==1.0.5
    - httpx==0.27.2
    - huggingface-hub==0.23.4
    - hydra-core==1.0.7
    - idna==3.4
    - importlib-metadata==6.0.0
    - importlib-resources==6.0.1
    - inflect==7.2.1
    - ipykernel==6.21.2
    - ipython==8.10.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - json5==0.9.25
    - jsonlines==3.1.0
    - jsonpointer==2.3
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.1
    - jupyter-core==5.2.0
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.2.5
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.5
    - kaggle==1.6.17
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lit==16.0.0
    - llvmlite==0.43.0
    - locket==1.0.0
    - lxml==4.9.2
    - markupsafe==2.1.2
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - more-itertools==10.3.0
    - mpld3==0.5.10
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - murmurhash==1.0.9
    - nbclassic==0.5.2
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - nltk==3.7
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.68
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.0.6
    - opentsne==1.0.2
    - overrides==7.7.0
    - packaging==23.0
    - pandas==2.2.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - partd==1.4.2
    - pathos==0.3.1
    - pathy==0.10.1
    - patsy==1.0.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - platformdirs==3.0.0
    - plotly==5.22.0
    - portalocker==2.7.0
    - pox==0.3.3
    - ppft==1.7.6.7
    - preshed==3.0.8
    - prettytable==3.10.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.37
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pycparser==2.21
    - pydantic==1.10.17
    - pyexecjs==1.5.1
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-slugify==8.0.4
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - referencing==0.35.1
    - regex==2022.10.31
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.20.0
    - s3transfer==0.10.2
    - sacrebleu==2.3.1
    - sacremoses==0.0.53
    - safetensors==0.4.3
    - scikit-learn==1.0.2
    - scipy==1.13.1
    - seaborn==0.12.2
    - send2trash==1.8.3
    - sentencepiece==0.2.0
    - six==1.16.0
    - smart-open==6.3.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4
    - spacy==3.7.5
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.5
    - stack-data==0.6.2
    - statsmodels==0.14.4
    - sympy==1.11.1
    - tabulate==0.9.0
    - tblib==3.0.0
    - tenacity==8.4.2
    - tensorboardx==2.6
    - terminado==0.17.1
    - text-unidecode==1.3
    - thinc==8.2.5
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.19.1
    - tomli==2.0.1
    - toolz==1.0.0
    - torch==2.4.0
    - torchaudio==2.4.0
    - torchvision==0.19.0
    - tornado==6.2
    - tqdm==4.66.5
    - traitlets==5.9.0
    - traittypes==0.2.1
    - transformers==4.44.2
    - triton==3.0.0
    - typeguard==4.3.0
    - typer==0.4.2
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - umap==0.1.1
    - uri-template==1.2.0
    - urllib3==1.26.14
    - wasabi==0.10.1
    - wcwidth==0.2.6
    - weasel==0.4.1
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.0.4
    - widgetsnbextension==4.0.5
    - xxhash==3.2.0
    - yarl==1.8.2
    - zict==3.0.0
    - zipp==3.14.0
